# Importation des packages

In [1]:
# Importation des packages
import pandas as pd
import numpy as np

# Création d'un data frame avec pandas

In [2]:
# Création du dictionnaire
etudiant = {"Prénom":["Donignon","Dotana","Chonny","Dramane","Kadohognon","Nadiala","Charles"]
           ,
           "Nom":["YEO","TUO","KONE","SORO","SILUE","OUATTARA","KOUASSI"],
           "Notes":[19,18,15,13,15,14,16.5]}
etudiant

{'Prénom': ['Donignon',
  'Dotana',
  'Chonny',
  'Dramane',
  'Kadohognon',
  'Nadiala',
  'Charles'],
 'Nom': ['YEO', 'TUO', 'KONE', 'SORO', 'SILUE', 'OUATTARA', 'KOUASSI'],
 'Notes': [19, 18, 15, 13, 15, 14, 16.5]}

In [3]:
# Transformer le dictionnaire en dataframe
df_etudiant=pd.DataFrame(etudiant)
df_etudiant

       Prénom       Nom  Notes
0    Donignon       YEO   19.0
1      Dotana       TUO   18.0
2      Chonny      KONE   15.0
3     Dramane      SORO   13.0
4  Kadohognon     SILUE   15.0
5     Nadiala  OUATTARA   14.0
6     Charles   KOUASSI   16.5

# Création à partir d'un fichier csv/excel

In [4]:
# Importaion du fichier csv
df=pd.read_csv("credit_risk_dataset.csv",sep=";")
df

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
0,1,40,Akono,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3
1,2,35,Akwa,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2
2,3,25,Arnaud,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3
3,4,23,Awa,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2
4,5,24,Dubois,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4
5,6,21,Durand,Bertin,9900,Locataire,CDD,A,2500,7.14,1,0.25,N,2
6,7,44,Ekounou,Eli,77100,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3
7,8,24,Mendong,Zibi,33000,Locataire,CDI,B,35000,11.11,1,0.44,N,4
8,9,24,Moussa,Hamado,24000,Locataire,CDI,A,35000,8.90,1,0.42,N,2
9,10,50,Mvog-ada,Bertin,80000,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3
10,11,22,Mvogo,Melanie,25000,Locataire,CDD,B,35000,10.37,1,0.41,N,4
11,12,21,Neba,Charlène,10000,Locataire,CDD,A,4500,8.63,1,0.45,N,2
12,13,34,Ngo,Stephanie,95000,Pret,CDI,A,35000,7.90,1,0.37,N,2
13,14,26,Ngono,Marie,108160,Pret,CDI,E,35000,18.39,1,0.32,N,4
14,15,23,Omar,Mohamed,115000,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4
15,16,32,Petit,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3
16,17,23,Richard,Arnaud,120000,Locataire,CDI,A,35000,7.90,0,0.29,N,4
17,18,31,Tchana,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4
18,19,23,Tchuente,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4
19,20,24,Yemba,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2

In [5]:
# Importation du fichier excel
df=pd.read_excel("credit_dataset_excel.xlsx")
df

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
0,1,40,Akono,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3
1,2,35,Akwa,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2
2,3,25,Arnaud,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3
3,4,23,Awa,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2
4,5,24,Dubois,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4
5,6,21,Durand,Bertin,9900,Locataire,CDD,A,2500,7.14,1,0.25,N,2
6,7,44,Ekounou,Eli,77100,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3
7,8,24,Mendong,Zibi,33000,Locataire,CDI,B,35000,11.11,1,0.44,N,4
8,9,24,Moussa,Hamado,24000,Locataire,CDI,A,35000,8.90,1,0.42,N,2
9,10,50,Mvog-ada,Bertin,80000,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3
10,11,22,Mvogo,Melanie,25000,Locataire,CDD,B,35000,10.37,1,0.41,N,4
11,12,21,Neba,Charlène,10000,Locataire,CDD,A,4500,8.63,1,0.45,N,2
12,13,34,Ngo,Stephanie,95000,Pret,CDI,A,35000,7.90,1,0.37,N,2
13,14,26,Ngono,Marie,108160,Pret,CDI,E,35000,18.39,1,0.32,N,4
14,15,23,Omar,Mohamed,115000,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4
15,16,32,Petit,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3
16,17,23,Richard,Arnaud,120000,Locataire,CDI,A,35000,7.90,0,0.29,N,4
17,18,31,Tchana,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4
18,19,23,Tchuente,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4
19,20,24,Yemba,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2

# Afficher un dataframe et afficher le type de données et description des colonnes

In [6]:
# Affichage des 5 premières lignes de notre dataFrame
df.head()

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
0,1,40,Akono,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3
1,2,35,Akwa,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2
2,3,25,Arnaud,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3
3,4,23,Awa,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2
4,5,24,Dubois,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4

In [7]:
#Afficher les 5 dernières lignes de notre dataFrame
df.tail(5)

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
15,16,32,Petit,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3
16,17,23,Richard,Arnaud,120000,Locataire,CDI,A,35000,7.90,0,0.29,N,4
17,18,31,Tchana,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4
18,19,23,Tchuente,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4
19,20,24,Yemba,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2

In [8]:
#voir la liste des colonnes du dataframe
df.columns

Index(['Id_personne', 'Age', 'Nom', 'Prenom', 'Revenu', 'Type de domicile',
       'Travail', 'Grade du pret', 'Montant du prêt', 'Taux_interet',
       'Statut_du_pret', 'Taux_endettement', 'Défaut',
       'Nombre de credit historique'],
      dtype='object')

In [9]:
#Voir le type de données de ma base de données

df.dtypes

Id_personne                      int64
Age                              int64
Nom                             object
Prenom                          object
Revenu                           int64
Type de domicile                object
Travail                         object
Grade du pret                   object
Montant du prêt                  int64
Taux_interet                   float64
Statut_du_pret                   int64
Taux_endettement               float64
Défaut                          object
Nombre de credit historique      int64
dtype: object

In [10]:
# Voir la dimension du tableau
df.shape

(20, 14)

# Lecture des tableaux pandas

## Sélectionner des colonnes

In [11]:
#Si la variable n'a pas d'espace
df.Id_personne.head(5)

0    1
1    2
2    3
3    4
4    5
Name: Id_personne, dtype: int64

In [12]:
#Si la variable a des caractères spéciaux
df['Type de domicile'].head(5)

0       Locataire
1    Propriétaire
2       Locataire
3            Pret
4            Pret
Name: Type de domicile, dtype: object

In [13]:
# Sélectionner plusieurs colonnes
new_df=df[['Type de domicile','Nom']]
new_df.head(4)

  Type de domicile     Nom
0        Locataire   Akono
1     Propriétaire    Akwa
2        Locataire  Arnaud
3             Pret     Awa

In [14]:
#Connaitre les valeurs uniques d'une variable
df['Type de domicile'].unique()

array(['Locataire', 'Propriétaire', 'Pret'], dtype=object)

# Sélectionner des lignes

In [15]:
#Sélectionner des lignes qui respectent une condition uniquement
new_cdi=df[df['Travail']=="CDI"]
new_cdi.head(5)

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
0,1,40,Akono,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3
1,2,35,Akwa,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2
3,4,23,Awa,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2
4,5,24,Dubois,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4
6,7,44,Ekounou,Eli,77100,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3

In [16]:
#Sélectionner des lignes avec plusieurs conditions
new_pret=df[(df['Travail']=="CDI") & (df['Grade du pret']=="D")]
new_pret.head(5)

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
0,1,40,Akono,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3
9,10,50,Mvog-ada,Bertin,80000,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3

# Indexation avec iloc (index location)

In [17]:
# Sélection de la première ligne
df.iloc[0]

Id_personne                            1
Age                                   40
Nom                                Akono
Prenom                            Nathan
Revenu                             59000
Type de domicile               Locataire
Travail                              CDI
Grade du pret                          D
Montant du prêt                    35000
Taux_interet                       16.02
Statut_du_pret                         1
Taux_endettement                    0.59
Défaut                                 Y
Nombre de credit historique            3
Name: 0, dtype: object

In [18]:
df.iloc[5]

Id_personne                            6
Age                                   21
Nom                               Durand
Prenom                            Bertin
Revenu                              9900
Type de domicile               Locataire
Travail                              CDD
Grade du pret                          A
Montant du prêt                     2500
Taux_interet                        7.14
Statut_du_pret                         1
Taux_endettement                    0.25
Défaut                                 N
Nombre de credit historique            2
Name: 5, dtype: object

In [19]:
df.iloc[16]

Id_personne                           17
Age                                   23
Nom                              Richard
Prenom                            Arnaud
Revenu                            120000
Type de domicile               Locataire
Travail                              CDI
Grade du pret                          A
Montant du prêt                    35000
Taux_interet                         7.9
Statut_du_pret                         0
Taux_endettement                    0.29
Défaut                                 N
Nombre de credit historique            4
Name: 16, dtype: object

In [20]:
# Sélectionner la dernière colone
df.iloc[-1]

Id_personne                        20
Age                                24
Nom                             Yemba
Prenom                         Elodie
Revenu                          10800
Type de domicile                 Pret
Travail                           CDD
Grade du pret                       B
Montant du prêt                  1750
Taux_interet                    10.99
Statut_du_pret                      1
Taux_endettement                 0.16
Défaut                              N
Nombre de credit historique         2
Name: 19, dtype: object

In [21]:
#Sélectionner les deux premières lignes et les deux première colonnes

df.iloc[0:2,0:2]

   Id_personne  Age
0            1   40
1            2   35

# Statistiques descriptives

# Obtenir des statistiques de base (moyenne, médiane, écart-type)

In [22]:
#Description des variables quantitatives
df.describe()

,Id_personne,Age,Revenu,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Nombre de credit historique
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,10.50000,28.450000,82503.550000,25092.500000,12.253500,0.800000,0.352500,3.050000
std,5.91608,8.274724,105576.833252,15036.274341,3.899438,0.410391,0.154507,0.887041
min,1.00000,21.000000,9600.000000,1000.000000,7.140000,0.000000,0.060000,2.000000
25%,5.75000,23.000000,24750.000000,5250.000000,8.832500,1.000000,0.280000,2.000000
50%,10.50000,24.000000,64500.000000,35000.000000,11.125000,1.000000,0.345000,3.000000
75%,15.25000,32.500000,98290.000000,35000.000000,14.862500,1.000000,0.450000,4.000000
max,20.00000,50.000000,500000.000000,35000.000000,20.250000,1.000000,0.590000,4.000000

# Compter les valeurs uniques et les fréquences

In [23]:
#Description des variables qualitatives
df.describe(include="object")

          Nom  Prenom Type de domicile Travail Grade du pret Défaut
count      20      20               20      20            20     20
unique     20      18                3       3             6      2
top     Akono  Bertin        Locataire     CDI             B      N
freq        1       2               10      11             6     18

In [24]:
#Compter les valeurs manquantes par variable
df.isnull().mean()

Id_personne                    0.0
Age                            0.0
Nom                            0.0
Prenom                         0.0
Revenu                         0.0
Type de domicile               0.0
Travail                        0.0
Grade du pret                  0.0
Montant du prêt                0.0
Taux_interet                   0.0
Statut_du_pret                 0.0
Taux_endettement               0.0
Défaut                         0.0
Nombre de credit historique    0.0
dtype: float64

# Modifier les données

## Suppression des lignes

In [25]:
#Suppression des lignes ayant des données manquantes
df.dropna(inplace=True)
df

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
0,1,40,Akono,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3
1,2,35,Akwa,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2
2,3,25,Arnaud,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3
3,4,23,Awa,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2
4,5,24,Dubois,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4
5,6,21,Durand,Bertin,9900,Locataire,CDD,A,2500,7.14,1,0.25,N,2
6,7,44,Ekounou,Eli,77100,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3
7,8,24,Mendong,Zibi,33000,Locataire,CDI,B,35000,11.11,1,0.44,N,4
8,9,24,Moussa,Hamado,24000,Locataire,CDI,A,35000,8.90,1,0.42,N,2
9,10,50,Mvog-ada,Bertin,80000,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3
10,11,22,Mvogo,Melanie,25000,Locataire,CDD,B,35000,10.37,1,0.41,N,4
11,12,21,Neba,Charlène,10000,Locataire,CDD,A,4500,8.63,1,0.45,N,2
12,13,34,Ngo,Stephanie,95000,Pret,CDI,A,35000,7.90,1,0.37,N,2
13,14,26,Ngono,Marie,108160,Pret,CDI,E,35000,18.39,1,0.32,N,4
14,15,23,Omar,Mohamed,115000,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4
15,16,32,Petit,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3
16,17,23,Richard,Arnaud,120000,Locataire,CDI,A,35000,7.90,0,0.29,N,4
17,18,31,Tchana,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4
18,19,23,Tchuente,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4
19,20,24,Yemba,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2

# Suppression des colonnes

In [26]:
#Supprimer une colonne

df.drop("Revenu",axis=1)

,Id_personne,Age,Nom,Prenom,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique
0,1,40,Akono,Nathan,Locataire,CDI,D,35000,16.02,1,0.59,Y,3
1,2,35,Akwa,Aicha,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2
2,3,25,Arnaud,Matin,Locataire,CDD,C,5500,12.87,1,0.57,N,3
3,4,23,Awa,Marie,Pret,CDI,C,35000,15.23,1,0.53,N,2
4,5,24,Dubois,Lachaise,Pret,CDI,C,35000,14.27,1,0.55,Y,4
5,6,21,Durand,Bertin,Locataire,CDD,A,2500,7.14,1,0.25,N,2
6,7,44,Ekounou,Eli,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3
7,8,24,Mendong,Zibi,Locataire,CDI,B,35000,11.11,1,0.44,N,4
8,9,24,Moussa,Hamado,Locataire,CDI,A,35000,8.90,1,0.42,N,2
9,10,50,Mvog-ada,Bertin,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3
10,11,22,Mvogo,Melanie,Locataire,CDD,B,35000,10.37,1,0.41,N,4
11,12,21,Neba,Charlène,Locataire,CDD,A,4500,8.63,1,0.45,N,2
12,13,34,Ngo,Stephanie,Pret,CDI,A,35000,7.90,1,0.37,N,2
13,14,26,Ngono,Marie,Pret,CDI,E,35000,18.39,1,0.32,N,4
14,15,23,Omar,Mohamed,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4
15,16,32,Petit,Prince,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3
16,17,23,Richard,Arnaud,Locataire,CDI,A,35000,7.90,0,0.29,N,4
17,18,31,Tchana,Albert,Locataire,CDD,F,35000,20.25,1,0.32,N,4
18,19,23,Tchuente,Isis,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4
19,20,24,Yemba,Elodie,Pret,CDD,B,1750,10.99,1,0.16,N,2

# Créer une nouvelle colonne calculer à partir d'autres

In [27]:
#Création d'une nouvelle variable comme étant la multiplication de deux colonnes du tableau
df["test"]=df["Montant du prêt"]*df["Taux_interet"]
df

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique,test
0,1,40,Akono,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3,560700.0
1,2,35,Akwa,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2,11140.0
2,3,25,Arnaud,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3,70785.0
3,4,23,Awa,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2,533050.0
4,5,24,Dubois,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4,499450.0
5,6,21,Durand,Bertin,9900,Locataire,CDD,A,2500,7.14,1,0.25,N,2,17850.0
6,7,44,Ekounou,Eli,77100,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3,434700.0
7,8,24,Mendong,Zibi,33000,Locataire,CDI,B,35000,11.11,1,0.44,N,4,388850.0
8,9,24,Moussa,Hamado,24000,Locataire,CDI,A,35000,8.90,1,0.42,N,2,311500.0
9,10,50,Mvog-ada,Bertin,80000,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3,23584.0
10,11,22,Mvogo,Melanie,25000,Locataire,CDD,B,35000,10.37,1,0.41,N,4,362950.0
11,12,21,Neba,Charlène,10000,Locataire,CDD,A,4500,8.63,1,0.45,N,2,38835.0
12,13,34,Ngo,Stephanie,95000,Pret,CDI,A,35000,7.90,1,0.37,N,2,276500.0
13,14,26,Ngono,Marie,108160,Pret,CDI,E,35000,18.39,1,0.32,N,4,643650.0
14,15,23,Omar,Mohamed,115000,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4,276500.0
15,16,32,Petit,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3,319500.0
16,17,23,Richard,Arnaud,120000,Locataire,CDI,A,35000,7.90,0,0.29,N,4,276500.0
17,18,31,Tchana,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4,708750.0
18,19,23,Tchuente,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4,638750.0
19,20,24,Yemba,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2,19232.5

# Mettre à jour une colonne

In [28]:
#Mettre à jour avec une valeur pour toutes les lignes
df["test"]=100
df

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique,test
0,1,40,Akono,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3,100
1,2,35,Akwa,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2,100
2,3,25,Arnaud,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3,100
3,4,23,Awa,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2,100
4,5,24,Dubois,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4,100
5,6,21,Durand,Bertin,9900,Locataire,CDD,A,2500,7.14,1,0.25,N,2,100
6,7,44,Ekounou,Eli,77100,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3,100
7,8,24,Mendong,Zibi,33000,Locataire,CDI,B,35000,11.11,1,0.44,N,4,100
8,9,24,Moussa,Hamado,24000,Locataire,CDI,A,35000,8.90,1,0.42,N,2,100
9,10,50,Mvog-ada,Bertin,80000,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3,100
10,11,22,Mvogo,Melanie,25000,Locataire,CDD,B,35000,10.37,1,0.41,N,4,100
11,12,21,Neba,Charlène,10000,Locataire,CDD,A,4500,8.63,1,0.45,N,2,100
12,13,34,Ngo,Stephanie,95000,Pret,CDI,A,35000,7.90,1,0.37,N,2,100
13,14,26,Ngono,Marie,108160,Pret,CDI,E,35000,18.39,1,0.32,N,4,100
14,15,23,Omar,Mohamed,115000,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4,100
15,16,32,Petit,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3,100
16,17,23,Richard,Arnaud,120000,Locataire,CDI,A,35000,7.90,0,0.29,N,4,100
17,18,31,Tchana,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4,100
18,19,23,Tchuente,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4,100
19,20,24,Yemba,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2,100

# Mettre à jour une valeur

In [29]:
#Mise à jour de la dernière colonne de la première ligne
df.iloc[0,-1]=100000
df

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique,test
0,1,40,Akono,Nathan,59000,Locataire,CDI,D,35000,16.02,1,0.59,Y,3,100000
1,2,35,Akwa,Aicha,70000,Propriétaire,CDI,B,1000,11.14,0,0.10,N,2,100
2,3,25,Arnaud,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3,100
3,4,23,Awa,Marie,44000,Pret,CDI,C,35000,15.23,1,0.53,N,2,100
4,5,24,Dubois,Lachaise,54400,Pret,CDI,C,35000,14.27,1,0.55,Y,4,100
5,6,21,Durand,Bertin,9900,Locataire,CDD,A,2500,7.14,1,0.25,N,2,100
6,7,44,Ekounou,Eli,77100,Propriétaire,CDI,B,35000,12.42,1,0.45,N,3,100
7,8,24,Mendong,Zibi,33000,Locataire,CDI,B,35000,11.11,1,0.44,N,4,100
8,9,24,Moussa,Hamado,24000,Locataire,CDI,A,35000,8.90,1,0.42,N,2,100
9,10,50,Mvog-ada,Bertin,80000,Propriétaire,CDI,D,1600,14.74,1,0.16,N,3,100
10,11,22,Mvogo,Melanie,25000,Locataire,CDD,B,35000,10.37,1,0.41,N,4,100
11,12,21,Neba,Charlène,10000,Locataire,CDD,A,4500,8.63,1,0.45,N,2,100
12,13,34,Ngo,Stephanie,95000,Pret,CDI,A,35000,7.90,1,0.37,N,2,100
13,14,26,Ngono,Marie,108160,Pret,CDI,E,35000,18.39,1,0.32,N,4,100
14,15,23,Omar,Mohamed,115000,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4,100
15,16,32,Petit,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3,100
16,17,23,Richard,Arnaud,120000,Locataire,CDI,A,35000,7.90,0,0.29,N,4,100
17,18,31,Tchana,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4,100
18,19,23,Tchuente,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4,100
19,20,24,Yemba,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2,100

# Mettre à jour des valeurs qui respectent une condition

In [30]:
#Modifier la valeur de la colonne d'une ligne en fonction d'une condition (remplacer D par F loan_grade)

df.loc[df["Travail"]=="CDI","Travail"]="CDD"
df

,Id_personne,Age,Nom,Prenom,Revenu,Type de domicile,Travail,Grade du pret,Montant du prêt,Taux_interet,Statut_du_pret,Taux_endettement,Défaut,Nombre de credit historique,test
0,1,40,Akono,Nathan,59000,Locataire,CDD,D,35000,16.02,1,0.59,Y,3,100000
1,2,35,Akwa,Aicha,70000,Propriétaire,CDD,B,1000,11.14,0,0.10,N,2,100
2,3,25,Arnaud,Matin,9600,Locataire,CDD,C,5500,12.87,1,0.57,N,3,100
3,4,23,Awa,Marie,44000,Pret,CDD,C,35000,15.23,1,0.53,N,2,100
4,5,24,Dubois,Lachaise,54400,Pret,CDD,C,35000,14.27,1,0.55,Y,4,100
5,6,21,Durand,Bertin,9900,Locataire,CDD,A,2500,7.14,1,0.25,N,2,100
6,7,44,Ekounou,Eli,77100,Propriétaire,CDD,B,35000,12.42,1,0.45,N,3,100
7,8,24,Mendong,Zibi,33000,Locataire,CDD,B,35000,11.11,1,0.44,N,4,100
8,9,24,Moussa,Hamado,24000,Locataire,CDD,A,35000,8.90,1,0.42,N,2,100
9,10,50,Mvog-ada,Bertin,80000,Propriétaire,CDD,D,1600,14.74,1,0.16,N,3,100
10,11,22,Mvogo,Melanie,25000,Locataire,CDD,B,35000,10.37,1,0.41,N,4,100
11,12,21,Neba,Charlène,10000,Locataire,CDD,A,4500,8.63,1,0.45,N,2,100
12,13,34,Ngo,Stephanie,95000,Pret,CDD,A,35000,7.90,1,0.37,N,2,100
13,14,26,Ngono,Marie,108160,Pret,CDD,E,35000,18.39,1,0.32,N,4,100
14,15,23,Omar,Mohamed,115000,Pret,Entreprenariat,A,35000,7.90,0,0.30,N,4,100
15,16,32,Petit,Prince,500000,Propriétaire,Entreprenariat,B,30000,10.65,0,0.06,N,3,100
16,17,23,Richard,Arnaud,120000,Locataire,CDD,A,35000,7.90,0,0.29,N,4,100
17,18,31,Tchana,Albert,92111,Locataire,CDD,F,35000,20.25,1,0.32,N,4,100
18,19,23,Tchuente,Isis,113000,Locataire,Entreprenariat,D,35000,18.25,1,0.31,N,4,100
19,20,24,Yemba,Elodie,10800,Pret,CDD,B,1750,10.99,1,0.16,N,2,100

# Fusion et jointure de Data Frames

In [31]:
# Création des DataFrames exemple
data1 = {
    "ID": [1, 2, 3, 4],
    "Prénom": ["Alice", "Bob", "Charlie", "David"]
}

data2 = {
    "ID": [3, 4, 5, 6],
    "Ville": ["Paris", "Lyon", "Marseille", "Toulouse"]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Effectuer une jointure interne (inner join)
inner_join = df1.merge(df2, on="ID", how="inner")

# Effectuer une jointure externe (outer join)
outer_join = df1.merge(df2, on="ID", how="outer")

# Effectuer une jointure gauche (left join)
left_join = df1.merge(df2, on="ID", how="left")

# Effectuer une jointure droite (right join)
right_join = df1.merge(df2, on="ID", how="right")

# Afficher les résultats
print("Inner join:")
print(inner_join)
print("\nOuter join:")
print(outer_join)
print("\nLeft join:")
print(left_join)
print("\nRight join:")
print(right_join)

Inner join:
   ID   Prénom  Ville
0   3  Charlie  Paris
1   4    David   Lyon

Outer join:
   ID   Prénom      Ville
0   1    Alice        NaN
1   2      Bob        NaN
2   3  Charlie      Paris
3   4    David       Lyon
4   5      NaN  Marseille
5   6      NaN   Toulouse

Left join:
   ID   Prénom  Ville
0   1    Alice    NaN
1   2      Bob    NaN
2   3  Charlie  Paris
3   4    David   Lyon

Right join:
   ID   Prénom      Ville
0   3  Charlie      Paris
1   4    David       Lyon
2   5      NaN  Marseille
3   6      NaN   Toulouse